data = [
    {"name": "Emma Johnson", "follower_count": 2_500_000, "country": "USA", "description": "Fashion Blogger and YouTuber"},
    {"name": "Liam Smith", "follower_count": 1_800_000, "country": "UK", "description": "Fitness Coach and Nutritionist"},
    {"name": "Sophia Chen", "follower_count": 3_200_000, "country": "Canada", "description": "Tech Reviewer and Entrepreneur"},
    {"name": "Carlos Rodriguez", "follower_count": 900_000, "country": "Spain", "description": "Travel Blogger and Photographer"},
    {"name": "Aisha Patel", "follower_count": 4_500_000, "country": "India", "description": "Bollywood Actress and Influencer"},
    {"name": "Noah Müller", "follower_count": 700_000, "country": "Germany", "description": "Gamer and Twitch Streamer"},
    {"name": "Isabelle Dubois", "follower_count": 2_100_000, "country": "France", "description": "Food Critic and Chef"},
    {"name": "Ethan Wright", "follower_count": 1_200_000, "country": "Australia", "description": "Extreme Sports Enthusiast"},
    {"name": "Mia Yamamoto", "follower_count": 3_800_000, "country": "Japan", "description": "Anime Artist and Digital Creator"},
    {"name": "Felix Svensson", "follower_count": 500_000, "country": "Sweden", "description": "DIY Home Projects and Crafts"},
    {"name": "Olivia Martínez", "follower_count": 5_000_000, "country": "Mexico", "description": "Beauty Guru and Makeup Artist"},
    {"name": "Jakub Kowalski", "follower_count": 750_000, "country": "Poland", "description": "Car Enthusiast and Mechanic"},
    {"name": "Samantha Lee", "follower_count": 2_700_000, "country": "Singapore", "description": "ASMR and Relaxation Content Creator"},
    {"name": "Leo Moretti", "follower_count": 1_900_000, "country": "Italy", "description": "Luxury Lifestyle and Watches"},
    {"name": "Tariq Al-Farsi", "follower_count": 850_000, "country": "UAE", "description": "Supercars and Motorsports"},
    {"name": "Amara Ndlovu", "follower_count": 1_500_000, "country": "South Africa", "description": "Wildlife Photographer and Conservationist"},
    {"name": "Victor Ivanov", "follower_count": 600_000, "country": "Russia", "description": "Cybersecurity Expert and Ethical Hacker"},
    {"name": "Hana Kim", "follower_count": 3_300_000, "country": "South Korea", "description": "K-Pop Dancer and Singer"},
    {"name": "Nathan Thompson", "follower_count": 1_100_000, "country": "New Zealand", "description": "Outdoor Survival and Bushcraft"},
    {"name": "Gabriella Costa", "follower_count": 2_400_000, "country": "Brazil", "description": "Samba Dancer and Carnival Performer"},
    {"name": "Diego Fernandez", "follower_count": 3_000_000, "country": "Argentina", "description": "Soccer Freestyler and Trick Shot Artist"},
    {"name": "Mei Ling", "follower_count": 4_700_000, "country": "China", "description": "Traditional Calligraphy and Painting"},
    {"name": "Haruto Tanaka", "follower_count": 950_000, "country": "Japan", "description": "Indie Game Developer and Pixel Artist"},
    {"name": "Elena Petrova", "follower_count": 1_350_000, "country": "Ukraine", "description": "Classical Pianist and Music Instructor"},
    {"name": "Mohamed Salah", "follower_count": 2_900_000, "country": "Egypt", "description": "Professional Footballer and Charity Worker"},
    {"name": "Daniel Park", "follower_count": 800_000, "country": "South Korea", "description": "Stand-up Comedian and Podcaster"},
    {"name": "Sofia Björk", "follower_count": 2_000_000, "country": "Norway", "description": "Winter Sports Athlete and Vlogger"},
    {"name": "Rajesh Kumar", "follower_count": 5_500_000, "country": "India", "description": "Spiritual Guru and Meditation Expert"},
    {"name": "Fatima Al-Mansoori", "follower_count": 1_750_000, "country": "Saudi Arabia", "description": "Fashion Designer and Entrepreneur"},
    {"name": "Elias Johansson", "follower_count": 1_050_000, "country": "Sweden", "description": "Music Producer and DJ"},
    {"name": "Alex Carter", "follower_count": 900_000, "country": "USA", "description": "Esports Commentator and Gaming Analyst"},
    {"name": "Sienna Rivera", "follower_count": 3_400_000, "country": "Colombia", "description": "Reggaeton Dancer and Social Media Star"},
    {"name": "Zhang Wei", "follower_count": 1_650_000, "country": "China", "description": "Martial Arts Instructor and Stunt Performer"},
    {"name": "Andrés Gomez", "follower_count": 2_300_000, "country": "Chile", "description": "Comedy Sketch Creator and Actor"},
    {"name": "Milan Kovac", "follower_count": 700_000, "country": "Czech Republic", "description": "Science Communicator and Astrophysicist"},
    {"name": "Luca Bianchi", "follower_count": 1_600_000, "country": "Italy", "description": "Culinary Chef and Michelin Star Critic"},
    {"name": "Yara Hussein", "follower_count": 2_800_000, "country": "Egypt", "description": "Fashion Model and Runway Influencer"},
    {"name": "Sebastian Schmidt", "follower_count": 1_400_000, "country": "Germany", "description": "Automotive Engineer and Car Reviewer"},
    {"name": "Chen Bao", "follower_count": 950_000, "country": "Taiwan", "description": "Traditional Tea Master and Educator"},
    {"name": "David Patel", "follower_count": 3_100_000, "country": "India", "description": "Start-up Entrepreneur and Investor"},
    {"name": "Lucía Ramírez", "follower_count": 2_100_000, "country": "Peru", "description": "Archaeologist and History Content Creator"},
    {"name": "Ivan Stojanovic", "follower_count": 1_250_000, "country": "Serbia", "description": "Chess Grandmaster and Strategy Coach"},
    {"name": "Amira Khaled", "follower_count": 3_500_000, "country": "Morocco", "description": "Henna Artist and Beauty Influencer"},
    {"name": "Kaito Nakamura", "follower_count": 2_600_000, "country": "Japan", "description": "AI Researcher and Robotics Engineer"}
]
